Task three
NearBirdSound/studSpringBoot pull request #3
Opened 2023-10-09 09:29 UTC by NearBirdSound

2023-10-09 18:23 UTC, se-nko requested changes

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/controller/FriendController.java
> +    private final FriendService fFind;
называть бины надо понятнее и обычно называют как класс - friendService

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/model/FriendDTO.java
> +    //@Pattern(regexp = "^[a-z ,.'-]+$")
Если закомментирован код и он не нужен, то удаляй, чтобы код был чистый

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    public FriendModel DTOtoModel(FriendDTO fd){
название методов всегда с маленькой буквы

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/tests/FriendConverterTest.java
> +    public void DTOtoModel() throws ParseException {
название методов тестов должны отражать что тестируем, например - testFriendsConvertToModel

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendConverter.java
> +public class FriendConverter {
Этот класс не должен быть сервисом в данном контексте, тут достаточно сделать его просто классом
А в классе где используешь, создаешь private static final FriendConverter CONVERTER = new FriendConverter()

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    private static FriendConverter FC;
тут паттерн синглтон не нужен

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    private FriendDTO fdCl = new FriendDTO();
Из полей класса должен остаться только DateFormat, создание объектов должно быть в методах, так как эти методы будут в памяти локально метода, это безопаснее с точки зрения многопоточности, тем более если ты его сервисом сделал

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendConverter.java
> +        dateStr = fd.getBirthDate();
Внутри метода надо создавать каэждый раз объект private FriendModel fmCl = new FriendModel();

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendService.java
> +    private static FriendService FS;
тут синглтон не нужен, обычнол сервис это просто сервис с методами и без синглтона.

2023-10-09 18:23 UTC, se-nko commented on src/main/java/com/example/demo/service/FriendService.java
> +    private static FriendService FS;
Синглтон используется в тех случаях, где нужен ровно один объект. Service в Spring будет в одном экземпляре на все входящие запросы, почитай про https://www.baeldung.com/spring-bean-scopes

2023-10-12 10:24 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendService.java
> +    private static FriendService FS;
сделал просто сервис

2023-10-12 10:24 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendConverter.java
> +        dateStr = fd.getBirthDate();
исправил

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    private FriendDTO fdCl = new FriendDTO();
оставил только датаформат перенес создание объектов в методы

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    private static FriendConverter FC;
исправил

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendConverter.java
> +public class FriendConverter {
сделал просто классом

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/tests/FriendConverterTest.java
> +    public void DTOtoModel() throws ParseException {
переименовал

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/service/FriendConverter.java
> +    public FriendModel DTOtoModel(FriendDTO fd){
переименовал

2023-10-12 10:25 UTC, NearBirdSound commented on src/main/java/com/example/demo/controller/FriendController.java
> +    private final FriendService fFind;
Переименовал

2023-10-13 06:30 UTC, se-nko commented on src/main/java/com/example/demo/controller/FriendController.java
> +    @Autowired
Зачем тут аннотация? ты создал статичную переменную, здесь не надо инжектить бин.

2023-10-13 12:23 UTC, merged